version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: online_store
    ports:
      - "5432:5432"
    volumes:
      - test_shop_db:/var/lib/postgresql/data

volumes:
  test_shop_db:
